# Generated by Django 5.1.7 on 2025-05-09 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_dash', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='image',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='video_file',
        ),
        migrations.AddField(
            model_name='lecture',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Paste unlisted YouTube video URL', null=True),
        ),
        migrations.CreateModel(
            name='LectureNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='lecture_notes/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='student_dash.lecture')),
            ],
        ),
    ]
