# Generated by Django 5.1.7 on 2025-04-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_facultycomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='img/user.jpg', upload_to='profile_pics/'),
        ),
    ]
