# Generated by Django 5.2.1 on 2025-05-31 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_course_faculty_alter_lecture_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='course_old',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='faculty_old',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
