# Generated by Django 5.2.1 on 2025-05-31 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_lecture_course_old_lecture_faculty_old'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='course_old',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='faculty_old',
        ),
    ]
