# Generated by Django 5.2.1 on 2025-05-31 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_remove_lecture_course_old_remove_lecture_faculty_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faculty',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
