# Generated by Django 5.2.1 on 2025-06-01 07:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_course_is_published_faculty_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultycomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_comments', to='classroom.faculty'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='institute',
            field=models.CharField(default='Institute Name', max_length=50),
        ),
        migrations.AddField(
            model_name='faculty',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='faculty',
            name='show_on_homepage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Facultie',
        ),
    ]
