# Generated by Django 5.2.1 on 2025-06-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0011_alter_facultycomment_post_faculty_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='institute',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
